### ISSUE TITLE
Raspberry pi 4 docker compose issue

### ISSUE THREAD

**Issue by JesseWebDotCom** [linuxserver/ifai#1176]
Trying to docker compose linuxserver/heimdall:latest and I get the following error:
The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested

I tried messing around with "platform" and different tags but I couldn't get it to work.

**Comment by thespad** [comment]
You're running a 32-bit OS which has had the kernel replaced with a 64-bit one - see https://github.com/raspberrypi/linux/issues/5402

As a result, docker is trying to find an `arm/v8` manifest, which doesn't exist because the native 64-bit arm manifest is `arm64`.

**Comment by JesseWebDotCom** [comment]
That was the issue (32bit os - which is the default option in the Raspberry Pi Image Manager).  I rebuilt with 64bit and Heimdall works fine.  Thanks - hopefully this issue helps someone else.

**Comment by MacUser341** [comment]
Can you where you're build? I have the same problem and I can't Install it on my Pi 4

**Comment by ItsJoshuaHirsch** [comment]
> Can you where you're build? I have the same problem and I can't Install it on my Pi 4


For me this worked: 
`docker pull linuxserver/heimdall --platform linux/arm64/v8`
So i modified the docker-compose.yml with this: 
**platform: linux/arm64/v8** 

=
```
services:
  heimdall: # Dashboard for all your Apps
    platform: linux/arm64/v8
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
...
```
