### ISSUE TITLE
Not loading correctly when run on a remote server

### ISSUE THREAD

**Issue by boi-doingthings** [linuxserver/ifai#1312]
I am trying to run heimdall on a remote server, to access few docker applications. despite issuing a lets encrypt cert, it shows up in a weird layout (probably due to inability in loading css/js files). The current view looks like:

![image](https://github.com/linuxserver/Heimdall/assets/111463360/65884a18-8d92-41de-b8d2-450abc3650da)

The docker compose looks like:
```
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
     - ./heimdall/:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 3010:80
      - 3011:443
    restart: unless-stopped
```

Further, the nginx conf file for the site looks like:

```
server {
    if ($host = heimdall.domain.tld) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name heimdall.domain.tld;
    return 301 https://$server_name$request_uri;


}

server {
    listen 443 ssl;
    server_name heimdall.domain.tld;


    ssl_certificate /etc/letsencrypt/live/heimdall.domain.tld/fullchain.pem; # managed by Certbot
 # manage>
    ssl_certificate_key /etc/letsencrypt/live/heimdall.domain.tld/privkey.pem; # managed by Certbot
 # man
    location / {
        proxy_pass http://localhost:3011;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}
```
It might not be an explicit issue, but looking forward for some help over here.
