### ISSUE TITLE
Support Kagi Search

### ISSUE THREAD

**Issue by pbronez** [linuxserver/ifai#1313]
I would like to use Kagi as the search provider in Heimdall.

Another user already did the work for this and submitted a pull request https://github.com/linuxserver/Heimdall/pull/1201

That pull request was auto-closed without review. I'd be happy to pick up the work from there if the maintainers are willing to review & merge.

**Comment by j0nnymoe** [comment]
No need, you can add your own via this: https://github.com/linuxserver/Heimdall?tab=readme-ov-file#search-providers

**Comment by pbronez** [comment]
Cool, thanks - that worked for me. For posterity, I added Kagi to Heimdall by adding:

```
kagi:
   id: kagi
   url: https://kagi.com/search
   name: Kagi
   method: get
   target: _blank
   query: q
```

to `/config/www/searchproviders.yaml`. Using Unraid, this is within `AppData/Heimdall` by default.
