### ISSUE TITLE
Does not start on freshly installed Ubuntu Server (General error: 5 database is locked)

### ISSUE THREAD

**Issue by BorisBrock** [linuxserver/ifai#1331]
I just set up a Ubuntu Server with docker. Then I added Heimdall via Portainer:

```
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /media/docker/heimdall:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```

But the container does not start up, and the web interface is not reachable. Here's what the container's log says:

> [migrations] started
> [migrations] 01-nginx-site-confs-default: skipped
> [migrations] 02-default-location: skipped
> [migrations] done
> ───────────────────────────────────────
>       ██╗     ███████╗██╗ ██████╗
>       ██║     ██╔════╝██║██╔═══██╗
>       ██║     ███████╗██║██║   ██║
>       ██║     ╚════██║██║██║   ██║
>       ███████╗███████║██║╚██████╔╝
>       ╚══════╝╚══════╝╚═╝ ╚═════╝
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> using keys found in /config/keys
> New container detected, installing Heimdall
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
>    Illuminate\Database\QueryException 
>   SQLSTATE[HY000]: General error: 5 database is locked (Connection: sqlite, SQL: create table "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null))
>   at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
>     825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
>     826▕                 );
>     827▕             }
>     828▕ 
>   ➜ 829▕             throw new QueryException(
>     830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
>     831▕             );
>     832▕         }
>     833▕     }
>   1   [internal]:0
>       Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
>       +41 vendor frames 
>   43  /app/www/app/Providers/AppServiceProvider.php:148
>       Illuminate\Support\Facades\Facade::__callStatic()

The SQL error then repeats indefinitely. Is there a cure for this?
