### ISSUE TITLE
[Feature Request] Let us add our own search providers

### ISSUE THREAD

**Issue by 825i** [linuxserver/ifai#1332]
First of all, thanks for the work on this template.

Yes I know it is possible to add a search provider in `appdata/heimdall/www/searchproviders.yaml`

**_But they are removed whenever the container is updated._**

Please give us the option to add these via the WebUI and that they would persist after an update.

For those reading, you can add your own search provider to Heimdall by going to the above config location and pasting in a new one at the bottom like so:

__________________________

Here is an example for my own self-hosted SearXNG

```
searxng:
   id: searx
   url: https://<yoururlhere>
   name: SearXNG
   method: post
   target: _blank
   query: q
```

![image](https://github.com/linuxserver/Heimdall/assets/58630825/f0dc6461-f227-4971-88ae-7d1765f6871a)

I use POST because it is more secure/private but you can also use "get" as usual.

It would be great if I could simply set this via the WebUI and it would stay that way.
