### ISSUE TITLE
Error 500 After some minutes running

### ISSUE THREAD

**Issue by lucasplcorrea** [linuxserver/ifai#1400]
I installed Heimdall via docker compose, but after a few minutes of running, when I try to access a list of users or applications I get a 500 error.

When I check the logs I have:

```
[2KHeimdall_BC2C  | [migrations] started
[2KHeimdall_BC2C  | [migrations] 01-nginx-site-confs-default: skipped
[2KHeimdall_BC2C  | [migrations] 02-default-location: skipped
[2KHeimdall_BC2C  | [migrations] done
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |       ██╗     ███████╗██╗ ██████╗
[2KHeimdall_BC2C  |       ██║     ██╔════╝██║██╔═══██╗
[2KHeimdall_BC2C  |       ██║     ███████╗██║██║   ██║
[2KHeimdall_BC2C  |       ██║     ╚════██║██║██║   ██║
[2KHeimdall_BC2C  |       ███████╗███████║██║╚██████╔╝
[2KHeimdall_BC2C  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |    Brought to you by linuxserver.io
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  | To support LSIO projects visit:
[2KHeimdall_BC2C  | https://www.linuxserver.io/donate/
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  | GID/UID
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  | User UID:    1000
[2KHeimdall_BC2C  | User GID:    1000
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  | Linuxserver.io version: v2.6.3-ls287
[2KHeimdall_BC2C  | Build-date: 2024-11-05T11:45:29+00:00
[2KHeimdall_BC2C  | ───────────────────────────────────────
[2KHeimdall_BC2C  |     
[2KHeimdall_BC2C  | using keys found in /config/keys
[2KHeimdall_BC2C  | New container detected, installing Heimdall
[2KHeimdall_BC2C  | [custom-init] No custom files found, skipping...
[2KHeimdall_BC2C  | [ls.io-init] done.
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |    GuzzleHttp\Exception\ConnectException 
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |   cURL error 28: Connection timed out after 15001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |   at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
[2KHeimdall_BC2C  |     206▕         }
[2KHeimdall_BC2C  |     207▕ 
[2KHeimdall_BC2C  |     208▕         // Create a connection exception if it was a specific error code.
[2KHeimdall_BC2C  |     209▕         $error = isset($connectionErrors[$easy->errno])
[2KHeimdall_BC2C  |   ➜ 210▕             ? new ConnectException($message, $easy->request, null, $ctx)
[2KHeimdall_BC2C  |     211▕             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
[2KHeimdall_BC2C  |     212▕ 
[2KHeimdall_BC2C  |     213▕         return P\Create::rejectionFor($error);
[2KHeimdall_BC2C  |     214▕     }
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |       [2m+13 vendor frames [22m
[2KHeimdall_BC2C  |   14  /app/www/app/SupportedApps.php:157
[2KHeimdall_BC2C  |       GuzzleHttp\Client::request()
[2KHeimdall_BC2C  | 
[2KHeimdall_BC2C  |   15  /app/www/app/Jobs/ProcessApps.php:41
[2KHeimdall_BC2C  |       App\SupportedApps::getList()
```

My docker-compose:

```
networks:
    1panel-network:
        external: true
services:
    heimdall:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TIME_ZONE}
        image: linuxserver/heimdall:2.6.3
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:80
            - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443
        restart: always
        volumes:
            - ./data:/config
```

After restarting the container it works for a few more minutes and stops working until it is restarted again.
